# Generated by Django 4.1.5 on 2023-03-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP1", "0002_alter_customer_insuranceduration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="InsuranceDuration",
            field=models.DateTimeField(),
        ),
    ]
