# Generated by Django 4.1.5 on 2023-03-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP1", "0003_alter_customer_insuranceduration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administration",
            fields=[
                (
                    "Role",
                    models.CharField(
                        choices=[
                            ("Sales manager", "Sales manager"),
                            ("Customer care associate", "Customer care associate"),
                            ("Call center agent", "Call center agent"),
                            ("Help desk assistant", "Help desk assistant"),
                        ],
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Passport", models.ImageField(upload_to="Management/")),
                ("DateRegistered", models.DateTimeField(auto_now_add=True)),
                ("Message", models.CharField(max_length=50)),
                ("Phone", models.CharField(max_length=50)),
            ],
        ),
    ]
